#!/bin/sh
# =============================================================================
# build-localized.sh - build inside a git-sdk-arm64 (CLANGARM64) environment
#                     a "fully localized ARM64 Git for Windows installer"
#
# Usage (called by GitHub Actions, running inside the SDK's bash --login):
#   <sdk>/usr/bin/bash.exe --login -c \
#     "cd <workdir> && ci/build-localized.sh <version> <workdir-win>"
#
# Dependencies (all provided with git-sdk-aarch64 ci-artifacts; if missing, see install_deps below):
#   - MSYS2/CLANGARM64 toolchain, git source build dependencies
#   - asciidoctor + parslet (ruby gem), po4a + perl modules
# =============================================================================
set -e

VERSION="$1"
WORKDIR_WIN="$2"          # Windows path, e.g. D:/a/build-extra/build-extra

die () { echo "ERROR: $*" >&2; exit 1; }

test -n "$VERSION" && test -n "$WORKDIR_WIN" ||
	die "Usage: build-localized.sh <version> <workdir-win>"

export MSYSTEM=CLANGARM64

# -----------------------------------------------------------------------------
# 0. Required tools/dependencies (idempotent; usually present in the CI image, this is a fallback)
# -----------------------------------------------------------------------------
install_deps () {
	# Install deps with pacman / direct package download (gem/CPAN are unreliable on CI:
	# gem install hits NameError, CPAN lacks network/build toolchain).
	# The image ships mingw-w64-clang-aarch64-asciidoctor.
	#  asciidoctor - renders man/html (needed by git-manpages-l10n and the English man fallback)
	command -v asciidoctor >/dev/null 2>&1 ||
		pacman -Sy --noconfirm asciidoctor || true
	# gettext-tools - msgmerge.exe etc. (merges the pot generated by po4a into each
	# language's po; the minimal CI SDK lacks it -> exit 127 command not found). clangarm64 repo package.
	# Note: bash's command -v does not auto-match .exe; must check with explicit .exe.
	{ command -v msgmerge >/dev/null 2>&1 ||
	  command -v msgmerge.exe >/dev/null 2>&1; } ||
		pacman -Sy --noconfirm mingw-w64-clang-aarch64-gettext-tools || true
	# python3 - scripts/set-priorities has a #!/usr/bin/python3 shebang; the CI
	# /usr/bin/python3 may be missing/invalid (/usr/bin may be read-only, writing a wrapper may fail).
	# Strategy (note: test -x must use explicit .exe; MSYS bash does not match .exe without suffix):
	#  1) Ensure clangarm64 python (install via pacman if missing, clangarm64 repo)
	#  2) After pacman, unconditionally overwrite the /usr/bin/python3 wrapper (pointing to python.exe)
	#  3) Rewrite set-priorities' shebang to /clangarm64/bin/python.exe
	#     (does not depend on /usr/bin being writable; most reliable)
	if test ! -x /clangarm64/bin/python.exe; then
		echo "WARN: no clangarm64 python, trying pacman install" >&2
		pacman -Sy --noconfirm mingw-w64-clang-aarch64-python || true
	fi
	if test -x /clangarm64/bin/python.exe; then
		rm -f /usr/bin/python3 2>/dev/null
		printf '#!/bin/sh\nexec /clangarm64/bin/python.exe "$@"\n' \
			> /usr/bin/python3 2>/dev/null
		chmod +x /usr/bin/python3 2>/dev/null
		test -x /usr/bin/python3 ||
			echo "WARN: failed to create /usr/bin/python3 (/usr/bin read-only?)" >&2
		if test -f "$L10N_SRC/scripts/set-priorities"; then
			sed -i '1s|^#!/usr/bin/python3$|#!/clangarm64/bin/python.exe|' \
				"$L10N_SRC/scripts/set-priorities" 2>/dev/null || true
			chmod +x "$L10N_SRC/scripts/set-priorities" 2>/dev/null || true
		fi
		# python polib - needed by set-priorities (import polib). polib.py is a
		# single-file pure-python module (MIT), vendored to ci/vendor/polib.py, copied into
		# clangarm64 python's site-packages (local MSYS python ships polib; CI has no MSYS
		# python, so it uses clangarm64 python and polib must be provided).
		if test -f "$BUILD_EXTRA/ci/vendor/polib.py"; then
			# Resolve the site-packages dir as an MSYS path (site.getsitepackages()
			# returns 'C:/...'; MSYS cp can usually write it, but keep the /clangarm64
			# form for consistency and to avoid path-conversion differences on CI)
			PYVER="$(/clangarm64/bin/python.exe -c 'import sys; print("python%d.%d" % sys.version_info[:2])' 2>/dev/null)"
			test -n "$PYVER" || PYVER=python3.14
			SP=/clangarm64/lib/$PYVER/site-packages
			mkdir -p "$SP"
			cp "$BUILD_EXTRA/ci/vendor/polib.py" "$SP/polib.py" 2>/dev/null || true
			/clangarm64/bin/python.exe -c 'import polib' >/dev/null 2>&1 ||
				echo "WARN: failed to copy python polib (set-priorities may fail)" >&2
		fi
	else
		echo "WARN: still no clangarm64 python, set-priorities will fail" >&2
	fi
	# po4a's perl module deps (YAML::Tiny / Text::WrapI18N / Unicode::LineBreak;
	# polib not needed - po4a parses po files with its bundled Locale::Po4a::Po).
	# The git-for-windows SDK's pacman has no [msys] repo mirror, `pacman -S` cannot find them ->
	# download .pkg.tar.zst directly from the official MSYS2 mirror and install via pacman -U
	# (note: package filenames keep case, e.g. perl-YAML-Tiny).
	if ! perl -MYAML::Tiny -e 1 >/dev/null 2>&1; then
		MSYS2_MIRROR=https://mirror.msys2.org/msys/x86_64
		# Under /var/cache/l10n-deps (not $HOME) so the CI workflow can cache it (actions/cache)
		PKG_DIR=/var/cache/l10n-deps/pkg
		mkdir -p "$PKG_DIR"
		# Try the pinned (reproducible) version first; if the SDK/upstream drifted and the
		# mirror dropped it, fall back to the newest matching package listed on the mirror.
		dl_pkg () { # $1 = pinned basename, $2 = package prefix for the newest-match fallback
			local base="$1" prefix="$2" newest
			test -f "$PKG_DIR/$base.pkg.tar.zst" && return 0
			curl -skL --connect-timeout 30 -o "$PKG_DIR/$base.pkg.tar.zst" \
				"$MSYS2_MIRROR/$base.pkg.tar.zst" && return 0
			rm -f "$PKG_DIR/$base.pkg.tar.zst"
			echo "WARN: $base missing on mirror, falling back to newest $prefix" >&2
			newest="$(curl -skL --connect-timeout 30 "$MSYS2_MIRROR/" |
				grep -oE "$prefix-[0-9][^-]*-[0-9]*-[^-]*\.pkg\.tar\.zst" |
				sort -V | tail -1)"
			test -n "$newest" &&
				curl -skL --connect-timeout 30 -o "$PKG_DIR/$newest" "$MSYS2_MIRROR/$newest" ||
				echo "WARN: no $prefix package found on $MSYS2_MIRROR" >&2
		}
		dl_pkg perl-YAML-Tiny-1.76-1-any perl-YAML-Tiny
		dl_pkg perl-Text-WrapI18N-0.06-2-any perl-Text-WrapI18N
		dl_pkg perl-Unicode-LineBreak-2019.001-8-x86_64 perl-Unicode-LineBreak
		pacman -U --noconfirm "$PKG_DIR"/perl-*.pkg.tar.zst || true
		perl -MYAML::Tiny -e 1 >/dev/null 2>&1 ||
			echo "WARN: perl-YAML-Tiny still unavailable (po4a may fail)" >&2
	fi
	# po4a (vendored to the git-manpages-l10n repo root). It is NOT cached: the
	# actions/cache round-trip can corrupt its layout (symlinks/perl module tree),
	# which made the l10n man build fail on specific languages (e.g. de). It is
	# tiny, so a clean clone on every build is cheap and deterministic.
	if test ! -x "$L10N_SRC/po4a/po4a"; then
		"$GIT" clone --depth 1 --branch v0.74 \
			https://github.com/mquinson/po4a "$L10N_SRC/po4a" 2>/dev/null ||
			echo "WARN: po4a clone failed" >&2
	fi
	# Patch: Po.pm concatenates the unescaped $reference into a regex for dedup;
	# perl 5.42 aborts on \p/\l/\m escape sequences ("Can't find Unicode property definition").
	# Escape reference with \Q..\E (idempotent; no-op if already patched).
	if test -f "$L10N_SRC/po4a/lib/Locale/Po4a/Po.pm"; then
		perl -pi -e '
			s{m/ \$reference /}{m/ \\Q\$reference\\E /};
			s{m/ \$reference\$/}{m/ \\Q\$reference\\E\$/};
			s{m/\^\$reference\$/}{m/^\\Q\$reference\\E\$/};
			s{m/\^\$reference /}{m/^\\Q\$reference\\E /};
		' "$L10N_SRC/po4a/lib/Locale/Po4a/Po.pm"
	fi
}

# -----------------------------------------------------------------------------
# 1. Locate sources (all three repos live under workdir, pre-cloned by the workflow)
# -----------------------------------------------------------------------------
cd "$WORKDIR_WIN" 2>/dev/null || cd "$(cygpath "$WORKDIR_WIN")" ||
	die "cannot enter workdir: $WORKDIR_WIN"

# MSYS path mapping
WIN=$(cygpath -m "$WORKDIR_WIN" 2>/dev/null || echo "$WORKDIR_WIN")
GIT_SRC="$WIN/git"
L10N_SRC="$WIN/git-manpages-l10n"
BUILD_EXTRA="$WIN/build-extra"
SDK_ROOT=/                        # inside the SDK bash, / is the SDK root

for d in "$GIT_SRC" "$L10N_SRC" "$BUILD_EXTRA"; do
	test -d "$d" || die "missing source directory: $d"
done

echo "==> version: $VERSION"
echo "==> git source: $GIT_SRC"
echo "==> l10n: $L10N_SRC"
echo "==> build-extra: $BUILD_EXTRA"

# Align the l10n version (upstream l10n drops the .windows suffix, e.g. 2.55.0)
L10N_VER="$(echo "$VERSION" | sed 's/\.windows\.[0-9]*//')"
echo "==> l10n aligned version: $L10N_VER"

# Use the MSYS-side git for git repo operations: the CI runner is x64, and the SDK's
# /clangarm64/bin/git is an ARM64 target binary that cannot run on this host.
GIT=/usr/bin/git
test -x "$GIT" || GIT=git

# ---- Reproducible build: pin TZ / locale / timestamps ----
# SOURCE_DATE_EPOCH is pinned to the git tag commit time (asciidoctor uses it for docdate,
# ensuring identical man/html content on every build of the same version, so the artifact SHA is stable).
export TZ=UTC
export LC_ALL=C.UTF-8
export SOURCE_DATE_EPOCH="$(cd "$GIT_SRC" && git log -1 --format=%ct 2>/dev/null || date +%s)"
GIT_DATE="$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%d 2>/dev/null || date -u +%Y-%m-%d)"
echo "==> reproducible build: SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH GIT_DATE=$GIT_DATE"

	# ---- Toolchain snapshot (printed for diagnostics; also saved to dist/sdk-info.txt at the
	#      end so every release records which SDK/toolchain it was built with) ----
	has_cmd () { command -v "$1" >/dev/null 2>&1 || command -v "$1.exe" >/dev/null 2>&1; }
	# probe prints "<tool>: <version>" only if the tool exists; under `set -e` a bare
	# `has_cmd X && echo` would abort the whole script when X is missing, so use `if`.
	probe () { if has_cmd "$1"; then echo "$1: $($1 --version 2>/dev/null | head -1)"; fi; }
	toolchain_snapshot () {
		{
			echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH"
			echo "git version: $("$GIT" --version 2>/dev/null)"
			probe clang
			probe gcc
			if has_cmd perl; then echo "perl: $(perl -e 'print $^V' 2>/dev/null)"; fi
			probe python3
			probe ruby
			probe asciidoctor
			probe msgmerge
			probe make
			if has_cmd pacman; then
				echo "pacman: $(pacman --version 2>/dev/null | tr '\r' ' ' | grep -m1 -oE 'Pacman v[0-9.]+')"
			fi
			# CI build-installers SDK may lack /etc/os-release; guard against set -e aborting
			if test -f /etc/os-release; then
				echo "sdk: $(grep -E '^(PRETTY_NAME|VERSION)=' /etc/os-release 2>/dev/null | tr '\n' '; ')"
			fi
		}
	}
	echo "==> toolchain snapshot:"
	toolchain_snapshot
cd "$GIT_SRC"
# The version was already checked out by the workflow at v$VERSION; no need to re-checkout
# Rust handling (use NO_RUST, matching official i686; functionally equivalent, varint etc. replaced by C):
#   Tried enabling Rust gitcore in CI, but the SDK (CLANGARM64) Rust toolchain is unreliable:
#     - `cargo build` crashes internally when calling `rustc -vV` (STATUS_ENTRYPOINT_NOT_FOUND,
#       missing companion DLLs; `rustc --version` passes but `-vV` crashes), so no gitcore lib is produced;
#     - even without the crash, `uname_S` under CLANGARM64 does not match the Windows branch of
#       config.mak.uname; the Makefile expects target/release/libgitcore.a, while cargo
#       (Windows host) produces target/release/gitcore.lib - name mismatch -> link failure.
#   Local builds (self-contained Rust toolchain) are unaffected and still include Rust gitcore.
echo "==> building git (NO_RUST, matching official i686; CI SDK Rust toolchain unavailable)"
make -j"$(nproc)" DEVELOPER=1 SKIP_DASHED_BUILT_INS=YesPlease NO_RUST=ThatsRight || die "git build failed"
# Note: install is a separate make process; it must also pass NO_RUST, otherwise the Makefile
# re-evaluates and GITLIBS includes $(RUST_LIB) (libgitcore.a), but cargo did not produce it -> link failure
make install DEVELOPER=1 SKIP_DASHED_BUILT_INS=YesPlease NO_RUST=ThatsRight || die "git install failed"

# -----------------------------------------------------------------------------
# 3. git-manpages-l10n: man pages + HTML docs for all translated languages (new languages picked up automatically)
# -----------------------------------------------------------------------------
echo "==> building l10n ..."
cd "$L10N_SRC"
# When python scripts (pre-translate-po/check_po etc.) print msgid/msgstr containing
# non-ASCII, Windows' default stdout encoding cp1252 crashes with UnicodeEncodeError -> force
# UTF-8 output (PYTHONUTF8=1).
export PYTHONUTF8=1
# actions/checkout defaults to autocrlf=true on Windows runners, converting repo text to
# CRLF -> script shebangs become `#!/usr/bin/python3^M` (bad interpreter), and the Makefile
# parses incorrectly. Set autocrlf=false and re-checkout as LF (po4a clone also inherits the global config).
"$GIT" config --global core.autocrlf false 2>/dev/null || true
"$GIT" config core.autocrlf false 2>/dev/null || true
# l10n was checked out to a pinned commit by the workflow via actions/checkout (reproducible); local builds use the current checkout state.
"$GIT" checkout -- . 2>/dev/null || true          # re-checkout as LF to overwrite any leftover CRLF working-tree files
install_deps

export GEM_HOME="$HOME/gems"
	# Resolve the SDK's system gem dir as an MSYS path (no drive letter). 'gem env
	# gempath' returns Windows-style 'C:/...;...' paths which break GEM_PATH's ':'
	# separator (ruby's gem glob then fails with Errno::EINVAL, breaking asciidoctor).
	# Glob the ruby version dir instead (dynamic, keeps the working /clangarm64 form).
	GEM_SYSDIR=
	for _d in /clangarm64/lib/ruby/gems/*; do
		test -d "$_d" && GEM_SYSDIR="$_d" && break
	done
	test -n "$GEM_SYSDIR" || GEM_SYSDIR=/clangarm64/lib/ruby/gems/4.0.0
	export GEM_PATH="$HOME/gems:$GEM_SYSDIR"
# Rendering man pages with asciidoctor needs asciidoctor-extensions.rb (makefile.locale loads
# it via `-rasciidoctor-extensions -I..` from the l10n root). git 2.55 only commits the
# asciidoctor-extensions.rb.in template; replace @GIT_VERSION@/@GIT_DATE@ to generate it
# (kept for older git that ships the .rb directly).
if test -f "$GIT_SRC/Documentation/asciidoctor-extensions.rb.in"; then
	sed -e "s|@GIT_VERSION@|$L10N_VER|g" \
		-e "s|@GIT_DATE@|$GIT_DATE|g" \
		"$GIT_SRC/Documentation/asciidoctor-extensions.rb.in" \
		> "$L10N_SRC/asciidoctor-extensions.rb" 2>/dev/null || true
elif test -f "$GIT_SRC/Documentation/asciidoctor-extensions.rb"; then
	cp "$GIT_SRC/Documentation/asciidoctor-extensions.rb" \
		"$L10N_SRC/asciidoctor-extensions.rb" 2>/dev/null || true
fi
make -j"$(nproc)" man || die "l10n man build failed"
make install-man mandir=/clangarm64/share/man || die "l10n man install failed"

make -j"$(nproc)" html || die "l10n html build failed"
make install-html prefix=/clangarm64/share/doc/git-doc || die "l10n html install failed"

# Simplified/Traditional Chinese mapping (man-db and help.htmlpath need zh_CN/zh_TW directories)
cp -r /clangarm64/share/man/zh_HANS-CN /clangarm64/share/man/zh_CN
cp -r /clangarm64/share/man/zh_HANT /clangarm64/share/man/zh_TW
cp -r /clangarm64/share/doc/git-doc/zh_HANS-CN /clangarm64/share/doc/git-doc/zh_CN
cp -r /clangarm64/share/doc/git-doc/zh_HANT /clangarm64/share/doc/git-doc/zh_TW

# -----------------------------------------------------------------------------
# 4. English man page fallback (git source Documentation)
# -----------------------------------------------------------------------------
echo "==> building English man fallback ..."
cd "$GIT_SRC/Documentation"
# Reuse the asciidoctor-extensions.rb generated at the l10n root (git's make man uses
# asciidoctor->xmlto, but the minimal CI SDK has no xmlto -> generate directly with asciidoctor -b manpage).
test -f asciidoctor-extensions.rb ||
	cp "$L10N_SRC/asciidoctor-extensions.rb" . 2>/dev/null || true
mkdir -p /clangarm64/share/man/man{1,5,7}
# Generate English man pages directly with asciidoctor -b manpage (consistent with l10n makefile.locale)
gen_man () { # $1=section $2=output basename $3=input adoc
	asciidoctor -b manpage -o "/clangarm64/share/man/man$1/$2.$1" \
		-d manpage -I. -rasciidoctor-extensions \
		-amanmanual='Git Manual' -amansource="Git $VERSION" \
		-amanversion="$VERSION" -alitdd='\--' -acompat-mode -atabsize=8 \
		-abuild_dir=. -amanvolnum="$1" "$3" 2>/dev/null || true
}
# man1: all git-*.adoc + git.adoc
for f in git-*.adoc git.adoc; do
	test -f "$f" || continue
	gen_man 1 "${f%.adoc}" "$f"
done
# man5 / man7: git 2.55's MAN5_TXT / MAN7_TXT
for f in gitattributes gitformat-bundle gitformat-chunk \
	gitformat-commit-graph gitformat-index gitformat-loose \
	gitformat-pack gitformat-signature githooks gitignore gitmailmap \
	gitmodules gitprotocol-capabilities gitprotocol-common \
	gitprotocol-http gitprotocol-pack gitprotocol-v2 \
	gitrepository-layout gitweb.conf; do
	test -f "$f.adoc" || continue
	gen_man 5 "$f" "$f.adoc"
done
for f in gitcli gitcore-tutorial gitcredentials gitcvs-migration \
	gitdatamodel gitdiffcore giteveryday gitfaq gitglossary gitpacking \
	gitnamespaces gitremote-helpers gitrevisions gitsubmodules \
	gittutorial-2 gittutorial gitworkflows; do
	test -f "$f.adoc" || continue
	gen_man 7 "$f" "$f.adoc"
done

# -----------------------------------------------------------------------------
# 5. Package the installer (the customized build-extra branch already enables WITH_L10N / man allow-listing / gcc-libs / keep-despite)
# -----------------------------------------------------------------------------
echo "==> packaging installer ..."
cd "$BUILD_EXTRA/installer"
unset GIT_EDITOR VISUAL EDITOR
mkdir -p "$WORKDIR_WIN/dist"
# ---- Reproducible: pin the mtime of every file to be packaged ----
# Inno Setup writes file timestamps into the installer; different mtime -> different installer bytes.
# Generate the file list with the same parameters as release.sh and touch every file to SOURCE_DATE_EPOCH.
# Use exactly the same ETC_GITCONFIG as release.sh (from git config --system -e, minus the leading /),
# so the touched file set == the file set release.sh actually packages.
etc_gitconfig="$(git -c core.editor=echo config --system -e 2>/dev/null)"
test -n "$etc_gitconfig" || etc_gitconfig=/etc/gitconfig
etc_gitconfig="$(cygpath -au "$etc_gitconfig" 2>/dev/null)"
etc_gitconfig="${etc_gitconfig#/}"
echo "==> etc_gitconfig=$etc_gitconfig"
TMP_TOUCH="/tmp/touched.$$"
TMP_FAIL="/tmp/touchfail.$$"
TMP_MFL="/tmp/mfllist.$$"
: > "$TMP_TOUCH"
: > "$TMP_FAIL"
(ARCH=aarch64 \
	ETC_GITCONFIG="$etc_gitconfig" \
	PACKAGE_VERSIONS_FILE=package-versions.txt \
	INCLUDE_GIT_UPDATE=1 WITH_L10N=1 \
	sh ../make-file-list.sh 2>/dev/null |
	tee "$TMP_MFL" |
	while IFS= read -r f
	do
		if test -e "/$f"; then
			# symlink: first touch -h to pin the link's own mtime, then touch to pin the target/regular file
			touch -h -d "@$SOURCE_DATE_EPOCH" "/$f" 2>/dev/null || true
			if touch -d "@$SOURCE_DATE_EPOCH" "/$f" 2>/dev/null; then
				echo x >>"$TMP_TOUCH"
			else
				echo "$f" >>"$TMP_FAIL"
			fi
		else
			echo "$f" >>"$TMP_FAIL"
		fi
	done)
echo "==> make-file-list total $(wc -l <"$TMP_MFL" 2>/dev/null || echo 0) files"
echo "==> pinned mtime for $(wc -l <"$TMP_TOUCH" 2>/dev/null || echo 0) files"
if test -s "$TMP_FAIL"; then
	echo "==> WARNING: touch failed for $(wc -l <"$TMP_FAIL") files (mtime not pinned; this affects reproducibility):"
	sed -n '1,80p' "$TMP_FAIL"
fi
rm -f "$TMP_TOUCH" "$TMP_FAIL" "$TMP_MFL"
# Reproducibility diagnostic: content checksum before packaging (must match across builds; a mismatch means file contents differ)
(cd "$BUILD_EXTRA/installer" && ARCH=aarch64 \
	ETC_GITCONFIG="$etc_gitconfig" \
	PACKAGE_VERSIONS_FILE=package-versions.txt \
	INCLUDE_GIT_UPDATE=1 WITH_L10N=1 \
	sh ../make-file-list.sh 2>/dev/null |
	while IFS= read -r f
	do
		test -f "/$f" && sha256sum "/$f"
	done | sort | sha256sum) | sed 's/^/==> content checksum: /'
cd "$BUILD_EXTRA/installer"    # the checksum above ran in a subshell; return to the directory
./release.sh --output="$WORKDIR_WIN/dist" "$VERSION" || die "installer build failed"

echo "==> done"
ls -lh "$WORKDIR_WIN"/dist/Git-"$VERSION"-arm64.exe
# Compute and print SHA256 (reproducibility check; the workflow can reference it)
(cd "$WORKDIR_WIN/dist" && sha256sum Git-*.exe | tee "Git-$VERSION-arm64.exe.sha256") 2>/dev/null || true	# Save the toolchain snapshot with the artifacts (uploaded alongside the .sha256 file; the
	# workflow publishes it in the release notes so each release records its build environment)
	toolchain_snapshot | tee "$WORKDIR_WIN/dist/sdk-info.txt"